### ISSUE TITLE
Gecut Todo Sample App Tasks

### ISSUE THREAD

**Issue by MM25Zamanian** [gecut/gecut#367]
# تسک اولیه

فونت صمیم رو روی سیستمتون نصب کنین که از خوندن بقیه متن لذت ببرید
از همین جا باید بگم هر کی صمیم نصب نکنه خره 💩

# تسک های بک اند

## انتقال ولیدیشن های بک اند به یک فایل

لطفا یه فایل به نام `validator` بساز و تمام ولیدیشن هارو به اون منتقل کن.

دقت کن هیچ ولیدینشی دیگه نباید توی فایل `app.ts` باشه

سخت ترین کارت انتخاب اسم برای ولیدیشن هاست 😁

## ساخت تایپ از روی ولیدیشین ها

بعد از اینکه همه ی ولیدیشن هارو منتقل کردی حالا باید از شون تایپ بسازی چون تو فرانت اند لازممون میشه

تایپ هارو از روی ولیدیشن به شکل زیر بساز.

‍
```ts
import { z } from 'zod';

export const todoInputValidation = z
  .object({
    status: z.boolean(),
    message: z.string(),
    id: z.string(),
    createdAt: z.number(),
    updatedAt: z.number(),
  })
  .partial({
    createdAt: true,
    updatedAt: true,
    id: true,
  });

// ساخت تایپ از روی ولیدیشن
export type TodoInputValidationType = z.TypeOf<typeof todoInputValidation>;
```

# تسک های فرانت اند

## کدت رو کمی عوض کردم و ساختار ui جیکات رو ریختم دور

چون لازمش نداری و باعث تولید paint flashing اضافه میشه
پس اول بفهم که چی به چیه

کدت هیچ تغییر خاصی نکرده فقط استایل هارو توی یه فایل دیگه گذاشتم به نام `app.element.css` و از ساختار پکیج مدیریت دیتای جیکات رو استفاده کردم

## حالا برو و داکیومنت مدیریت دیتای جیکات رو بخون

پیدا کردن داکیومنتش رو میسپارم به هوش سرشارت
ولی توی فایل `README.md` خوده پکیجش هست

# کلام آخر

اول اینکه دلم براتون تنگ شده ❤️

و بعد لطفا توی انجام تسک های به هم کمک کنین هیچ مانعی نداره
و حتما جفتتون مدیریت دیتای جیکات رو بخونین شاهکاره

اگر سوالی داشتین تلگرامم بپرسین سعی میکنم جواب بدم ولی چرت نباشه لطفا

اگر این تسک های تا برگشت من تموم نشه یه بستنی قیفی از هرکدوم تون میگیرم 🍦😋
با توجه به هوای عراق دلم برای بستنی تنگ میشه

**Comment by MM25Zamanian** [comment]
الان که دقت میکنم خودم صمیم رو نصب ندارم !

**Comment by ArmanAsadian** [comment]
من نصب کردم ولی اینکه چطوری بتونم ست کنم رو هنوز پیدا نکردم😁
